# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          mkdir -p ./asset/json ./asset/json/comments
          wget "https://api.github.com/repos/$GITHUB_REPOSITORY/issues?state=all&labels=displayed-issue" -O ./asset/json/displayed-issues.json
          wget "https://api.github.com/repos/$GITHUB_REPOSITORY/issues?state=all&labels=maintenance" -O ./asset/json/maintenances.json
          node ./.github/workflows/cleanup_issues_json.js ./asset/json/displayed-issues.json
          node ./.github/workflows/cleanup_issues_json.js ./asset/json/maintenances.json
          jq -s '.[][]' ./asset/json/displayed-issues.json ./asset/json/maintenances.json | jq -s -S 'sort_by(.number) | reverse' > ./asset/json/issues.json
          bash ./.github/workflows/fetch_comments.sh
  
