# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch issues to json
        run: |
          mkdir -p asset/json
          wget https://api.github.com/repos/$GITHUB_REPOSITORY/issues?labels=displayed-issue -O asset/json/displayed-issues.json
          wget https://api.github.com/repos/$GITHUB_REPOSITORY/issues?labels=maintenance -O asset/json/maintenances.json
          
      - name: Commit json files
        run: |
          git add displayed-issues.json
          git add maintenance.json
          git commit -m "Auto updating json files"
          
      - name: Push json files
        uses: ad-m/ithub-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
